/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registro.académico;

import javax.swing.JOptionPane;

/**
 *
 * @author EDWARD
 */
public class RegistroAcadémicoGui extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroAcadémicoGui.class.getName());

    /**
     * Creates new form RegistroAcadémicoGui
     */
    public RegistroAcadémicoGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        DatosEstudiante = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPracticas = new javax.swing.JTextField();
        txtParciales = new javax.swing.JTextField();
        txtAsignaciones = new javax.swing.JTextField();
        txtExamenFinal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnSumar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        txtMensaje = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plTitulo.setBackground(new java.awt.Color(0, 153, 153));
        plTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registro Académico");
        plTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        DatosEstudiante.setBackground(new java.awt.Color(153, 153, 153));
        DatosEstudiante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 102, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Datos del estudiante");
        DatosEstudiante.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        DatosEstudiante.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Matricula:");
        DatosEstudiante.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.addActionListener(this::txtNombreActionPerformed);
        DatosEstudiante.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, 30));

        txtMatricula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMatricula.addActionListener(this::txtMatriculaActionPerformed);
        DatosEstudiante.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 150, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Carrera:");
        DatosEstudiante.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtCarrera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCarrera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DatosEstudiante.add(txtCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 150, 30));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(51, 51, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Calificaciones");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 6, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Prácticas:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Parciales:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Asignaciones:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Examen Final:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        txtPracticas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPracticas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPracticas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPracticasKeyTyped(evt);
            }
        });
        jPanel1.add(txtPracticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 140, 30));

        txtParciales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtParciales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtParciales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParcialesKeyTyped(evt);
            }
        });
        jPanel1.add(txtParciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, 30));

        txtAsignaciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAsignaciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAsignaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAsignacionesKeyTyped(evt);
            }
        });
        jPanel1.add(txtAsignaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 140, 30));

        txtExamenFinal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtExamenFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtExamenFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExamenFinalKeyTyped(evt);
            }
        });
        jPanel1.add(txtExamenFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 140, 30));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSumar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSumar.setText("Calcular resultado");
        btnSumar.addActionListener(this::btnSumarActionPerformed);
        jPanel2.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Nota total:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        txtNota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNota.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 120, 30));

        txtMensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMensaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 140, 30));

        jButton1.setText("Limpiar Campos");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DatosEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(plTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DatosEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtPracticasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPracticasKeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9')){
                JOptionpane.showMessageDialog(null, "El numero debe ser un entero");
                evt.consume();
        }
    }//GEN-LAST:event_txtPracticasKeyTyped

    private void txtParcialesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParcialesKeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9')){
            JOptionpane.showMessageDialog(null, "El numero debe ser un entero");
            evt.consume();
    }
    }//GEN-LAST:event_txtParcialesKeyTyped

    private void txtAsignacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAsignacionesKeyTyped
        char numeros = evt.getKeyChar();
        if((numeros < '0' || numeros > '9')){
            JOptionpane.showMessageDialog(null, "El numero debe ser un entero");
            evt.consume();
        }
    }//GEN-LAST:event_txtAsignacionesKeyTyped

    private void txtExamenFinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExamenFinalKeyTyped
        char numeros = evt.getKeyChar();
        if((numeros < '0' || numeros > '9')){
            JOptionpane.showMessageDialog(null, "El numero debe ser un entero");
            evt.consume();
        }
    }//GEN-LAST:event_txtExamenFinalKeyTyped

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        
        sumarValores();
    }//GEN-LAST:event_btnSumarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jButton1ActionPerformed
    
  
    
    private void sumarValores(){
        
    
    try {
        if (txtNombre.getText().isEmpty() ||
            txtMatricula.getText().isEmpty() ||
            txtCarrera.getText().isEmpty() ||
            txtPracticas.getText().isEmpty() ||
            txtParciales.getText().isEmpty() ||
            txtAsignaciones.getText().isEmpty() ||
            txtExamenFinal.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos");
            return;
        }

        double practicas = Double.parseDouble(txtPracticas.getText());
        double parciales = Double.parseDouble(txtParciales.getText());
        double asignaciones = Double.parseDouble(txtAsignaciones.getText());
        double examen = Double.parseDouble(txtExamenFinal.getText());

        if (practicas > 40 || parciales > 20 || asignaciones > 20 || examen > 20) {
            JOptionPane.showMessageDialog(null, "Valores fuera de rango permitido");
            return;
        }

    Estudiante est = new Estudiante(
    txtNombre.getText(),
    txtMatricula.getText(),
    txtCarrera.getText(),
    practicas, parciales, asignaciones, examen
);

double total = est.calcularNotaFinal();

txtNota.setText(String.valueOf(total));
txtMensaje.setText(est.getResultado());

        txtNota.setText(String.valueOf(total));

        if (total >= 60) {
            txtMensaje.setText("APROBADO");
        } else {
            txtMensaje.setText("REPROBADO");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese solo números válidos");
    }
        
    }
    
    private void limpiarCampos(){
        txtPracticas.setText("");
        txtParciales.setText("");
        txtAsignaciones.setText("");
        txtExamenFinal.setText("");
        txtNota.setText("");
        txtMensaje.setText("");
        txtNombre.setText("");
        txtMatricula.setText("");
        txtCarrera.setText("");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroAcadémicoGui().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DatosEstudiante;
    private javax.swing.JButton btnSumar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel plTitulo;
    private javax.swing.JTextField txtAsignaciones;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtExamenFinal;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMensaje;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtParciales;
    private javax.swing.JTextField txtPracticas;
    // End of variables declaration//GEN-END:variables
}
