/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EDWARD
 */
public class calculadorabásicaGui extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(calculadorabásicaGui.class.getName());

    /**
     * Creates new form calculadorabásicaGui
     */
    public calculadorabásicaGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btSuma = new javax.swing.JButton();
        btResta = new javax.swing.JButton();
        btMultiplicar = new javax.swing.JButton();
        btDividir = new javax.swing.JButton();
        btCelcius = new javax.swing.JButton();
        btFahrenheit = new javax.swing.JButton();
        btRaiz = new javax.swing.JButton();
        btExponente = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 20, 288, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Valor 1");

        txtValor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor1KeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Valor 2");

        txtValor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor2KeyTyped(evt);
            }
        });

        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Resultado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValor2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel4)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSuma.setText("Suma");
        btSuma.addActionListener(this::btSumaActionPerformed);
        jPanel3.add(btSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, 40));

        btResta.setText("Resta");
        btResta.addActionListener(this::btRestaActionPerformed);
        jPanel3.add(btResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 100, 40));

        btMultiplicar.setText("Multiplicar");
        btMultiplicar.addActionListener(this::btMultiplicarActionPerformed);
        jPanel3.add(btMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 100, 40));

        btDividir.setText("Dividir");
        btDividir.addActionListener(this::btDividirActionPerformed);
        jPanel3.add(btDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 100, 40));

        btCelcius.setText("°C - °F");
        btCelcius.addActionListener(this::btCelciusActionPerformed);
        jPanel3.add(btCelcius, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 100, 40));

        btFahrenheit.setText("°F - °C  ");
        btFahrenheit.addActionListener(this::btFahrenheitActionPerformed);
        jPanel3.add(btFahrenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 100, 40));

        btRaiz.setText("Raíz cuadrada");
        btRaiz.addActionListener(this::btRaizActionPerformed);
        jPanel3.add(btRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 100, 40));

        btExponente.setText("Exponente");
        btExponente.addActionListener(this::btExponenteActionPerformed);
        jPanel3.add(btExponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 100, 40));

        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(this::btLimpiarActionPerformed);
        jPanel3.add(btLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 150, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')){
            JOptionpane.showMessageDialog(null, "Ingrese un numero para realizar operacion");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor1KeyTyped

    private void txtValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor2KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')){
            JOptionpane.showMessageDialog(null, "Ingrese un numero para realizar operacion");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor2KeyTyped

    private void btSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSumaActionPerformed
        validarCampos();
        sumarValores();
    }//GEN-LAST:event_btSumaActionPerformed

    private void btRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRestaActionPerformed
        validarCampos();
        restarValores();
    }//GEN-LAST:event_btRestaActionPerformed

    private void btMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultiplicarActionPerformed
        validarCampos();
        multiplicarValores();
    }//GEN-LAST:event_btMultiplicarActionPerformed

    private void btDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDividirActionPerformed
        validarCampos();
        dividirValores();
    }//GEN-LAST:event_btDividirActionPerformed

    private void btCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCelciusActionPerformed
        convertirFahrenheit();
    }//GEN-LAST:event_btCelciusActionPerformed

    private void btFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFahrenheitActionPerformed
        convertirCelsius();
    }//GEN-LAST:event_btFahrenheitActionPerformed

    private void btRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRaizActionPerformed
        raizNumero();
    }//GEN-LAST:event_btRaizActionPerformed

    private void btExponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExponenteActionPerformed
        exponenteNumero();
    }//GEN-LAST:event_btExponenteActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void validarCampos(){
        if(txtValor1.getText().trim().length() <= 0){
            JOptionpane.showMessageDialog(null, "Ingrese valor 1 por que esta vacio");
            txtValor1.requestFocus();
    } else if(txtValor2.getText().trim().length() <= 0){
            JOptionpane.showMessageDialog(null, "Ingrese valor 1 por que esta vacio");
            txtValor1.requestFocus();
    }
    }
    
    private void sumarValores(){
        Calculadora cal = new Calculadora();
        double respuesta = cal.sumar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtResultado.setText(respuesta + "");
    }
    
    private void restarValores(){
        Calculadora cal = new Calculadora();
        double respuesta = cal.restar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtResultado.setText(respuesta + "");
    }
    
    private void multiplicarValores(){
        Calculadora cal = new Calculadora();
        double respuesta = cal.multiplicar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtResultado.setText(respuesta + "");
    }
    
    private void dividirValores(){
        Calculadora cal = new Calculadora();
        double respuesta = cal.dividir(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtResultado.setText(respuesta + "");
    }
    
    private void convertirFahrenheit(){
        Calculadora cal = new Calculadora();
        double respuesta = cal.fahrenheit(Double.parseDouble(txtValor1.getText()));
        txtResultado.setText(respuesta + " °F");
    }
    
    private void convertirCelsius(){
        Calculadora cal = new Calculadora();
        double respuesta = cal.celsius(Double.parseDouble(txtValor1.getText()));
        txtResultado.setText(respuesta + " °C");
    }
    
    private void raizNumero(){
        Calculadora cal = new Calculadora();
        double respuesta = cal.raiz(Double.parseDouble(txtValor1.getText()));
        txtResultado.setText(respuesta + "");
    }
    
    private void exponenteNumero(){
        Calculadora cal = new Calculadora();
        double respuesta = cal.exponente(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtResultado.setText(respuesta + "");
    }
    
    private void limpiarCampos(){
        txtValor1.setText("");
        txtValor2.setText("");
        txtResultado.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new calculadorabásicaGui().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCelcius;
    private javax.swing.JButton btDividir;
    private javax.swing.JButton btExponente;
    private javax.swing.JButton btFahrenheit;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btMultiplicar;
    private javax.swing.JButton btRaiz;
    private javax.swing.JButton btResta;
    private javax.swing.JButton btSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
