
import com.mycompany.calculadoragui.Calculadora;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DAWRY13
 */
public class CalculadoraGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName());

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMultiplicar4 = new javax.swing.JButton();
        plTitulo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        plValores = new javax.swing.JPanel();
        LblValor1 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        lblValor2 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        lblRespuestas = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        plOperaciones = new javax.swing.JPanel();
        btnResetear = new javax.swing.JButton();
        btnSumar1 = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnConversor2 = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        btnPotencia = new javax.swing.JButton();
        btnConversorTemperatura = new javax.swing.JButton();

        btnMultiplicar4.setText("Multiplicar");
        btnMultiplicar4.addActionListener(this::btnMultiplicar4ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plTitulo.setBackground(new java.awt.Color(102, 102, 102));
        plTitulo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                plTituloAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        plTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("CALCULADORA");
        plTitulo.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 51, 63));

        getContentPane().add(plTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        plValores.setBackground(new java.awt.Color(153, 153, 153));
        plValores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblValor1.setBackground(new java.awt.Color(0, 0, 0));
        LblValor1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LblValor1.setForeground(new java.awt.Color(0, 0, 0));
        LblValor1.setText("Valor 1:");
        plValores.add(LblValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 40));

        txtValor1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtValor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor1.addActionListener(this::txtValor1ActionPerformed);
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor1KeyTyped(evt);
            }
        });
        plValores.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, 40));

        lblValor2.setBackground(new java.awt.Color(0, 0, 0));
        lblValor2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lblValor2.setForeground(new java.awt.Color(0, 0, 0));
        lblValor2.setText("Valor 2:");
        plValores.add(lblValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 40));

        txtValor2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtValor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor2.addActionListener(this::txtValor2ActionPerformed);
        txtValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor2KeyTyped(evt);
            }
        });
        plValores.add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 140, 40));

        lblRespuestas.setBackground(new java.awt.Color(0, 0, 0));
        lblRespuestas.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lblRespuestas.setForeground(new java.awt.Color(0, 0, 0));
        lblRespuestas.setText("Respuestas");
        plValores.add(lblRespuestas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 140, 40));

        txtRespuesta.setEditable(false);
        txtRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtRespuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRespuesta.addActionListener(this::txtRespuestaActionPerformed);
        txtRespuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRespuestaKeyTyped(evt);
            }
        });
        plValores.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 200, 80));

        getContentPane().add(plValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 290, 360));

        plOperaciones.setBackground(new java.awt.Color(204, 204, 204));
        plOperaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnResetear.setText("Resetear");
        btnResetear.addActionListener(this::btnResetearActionPerformed);
        plOperaciones.add(btnResetear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 210, 50));

        btnSumar1.setText("Sumar");
        btnSumar1.addActionListener(this::btnSumar1ActionPerformed);
        plOperaciones.add(btnSumar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 50));

        btnRestar.setText("Restar");
        btnRestar.addActionListener(this::btnRestarActionPerformed);
        plOperaciones.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 130, 50));

        btnConversor2.setText("°F  ↔ °C");
        btnConversor2.addActionListener(this::btnConversor2ActionPerformed);
        plOperaciones.add(btnConversor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 130, 50));

        btnDividir.setText("Dividir");
        btnDividir.addActionListener(this::btnDividirActionPerformed);
        plOperaciones.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 130, 50));

        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(this::btnMultiplicarActionPerformed);
        plOperaciones.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 50));

        btnRaiz.setText("Raiz cuadrada");
        btnRaiz.addActionListener(this::btnRaizActionPerformed);
        plOperaciones.add(btnRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, 50));

        btnPotencia.setText("Potencia");
        btnPotencia.addActionListener(this::btnPotenciaActionPerformed);
        plOperaciones.add(btnPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 130, 50));

        btnConversorTemperatura.setText("°C ↔ °F");
        btnConversorTemperatura.addActionListener(this::btnConversorTemperaturaActionPerformed);
        plOperaciones.add(btnConversorTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 50));

        getContentPane().add(plOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 290, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void txtValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor2ActionPerformed
        
    }//GEN-LAST:event_txtValor2ActionPerformed

    private void txtRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuestaActionPerformed
       
    }//GEN-LAST:event_txtRespuestaActionPerformed

    /**
     * Validación: solo permite números en el campo valor 1
     */
    private void txtValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyTyped
        char numeros = evt.getKeyChar();
        if((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')){
        JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion");
        evt.consume();
    }
    }//GEN-LAST:event_txtValor1KeyTyped

    /**
     * Validación: solo permite números en el campo valor 2
     */
    private void txtValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor2KeyTyped
       char numeros = evt.getKeyChar();
        if((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')){
        JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion");
        evt.consume();
    }
    }//GEN-LAST:event_txtValor2KeyTyped

    // ==========================
    // BOTONES DE OPERACIONES
    // ==========================
    
    private void btnSumar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumar1ActionPerformed
        validarCampos();
        SumarValores();
    }//GEN-LAST:event_btnSumar1ActionPerformed

    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
      limpiarCampos();
    }//GEN-LAST:event_btnResetearActionPerformed

    private void txtRespuestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRespuestaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaKeyTyped

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        validarCampos();
        RestarValores();
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnConversor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConversor2ActionPerformed
           try{
        double f = Double.parseDouble(txtValor1.getText());
        double c = (f - 32) * 5 / 9;

        txtRespuesta.setText(c + "");

    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Ingrese un valor válido");
    }
    }//GEN-LAST:event_btnConversor2ActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        validarCampos();
        DividirValores();
    }//GEN-LAST:event_btnDividirActionPerformed

    private void plTituloAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_plTituloAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_plTituloAncestorAdded

    // ==========================
    // OPERACIONES ESPECIALES
    // ==========================
    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
            try{
        double num = Double.parseDouble(txtValor1.getText());

        if(num < 0){
            JOptionPane.showMessageDialog(null, "No se puede calcular raíz de número negativo");
            return;
        }

        double res = Math.sqrt(num);
        txtRespuesta.setText(res + "");

    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Ingrese un número válido");
    }
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaActionPerformed
            try{
        double base = Double.parseDouble(txtValor1.getText());
        double exponente = Double.parseDouble(txtValor2.getText());

        double res = Math.pow(base, exponente);
        txtRespuesta.setText(res + "");

    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Ingrese valores válidos");
    }
    }//GEN-LAST:event_btnPotenciaActionPerformed

    private void btnMultiplicar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultiplicar4ActionPerformed

    private void btnConversorTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConversorTemperaturaActionPerformed
           try{
        double c = Double.parseDouble(txtValor1.getText());
        double f = (c * 9 / 5) + 32;

        txtRespuesta.setText(f + "");

    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Ingrese un valor válido");
    }
    }//GEN-LAST:event_btnConversorTemperaturaActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        validarCampos();
        MultiplicarValores();
    }//GEN-LAST:event_btnMultiplicarActionPerformed
    

    // ==========================
    // VALIDACIÓN DE CAMPOS
    // ==========================
    private void validarCampos(){
        if(txtValor1.getText().trim().length() <=0){
           JOptionPane.showMessageDialog(null, "Favor ingresar valor 1, porque el campo esta vacio.");
           txtValor1.requestFocus();
        } else if(txtValor2.getText().trim().length() <=0){
           JOptionPane.showMessageDialog(null, "Favor ingresar valor 2, porque el campo esta vacio.");
           txtValor2.requestFocus();
        }
    }
    
    
    // ==========================
    // METODOS DE OPERACIONES
    // ==========================
    private void SumarValores(){
        Calculadora cal = new Calculadora();
        Double respuesta = cal.sumar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta +"");
    }
    
    
    
      private void RestarValores(){
        Calculadora cal = new Calculadora();
        Double respuesta = cal.restar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta +"");
    }
      
    
      private void MultiplicarValores(){
        Calculadora cal = new Calculadora();
        Double respuesta = cal.multiplicar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta +"");
    }
      
      private void DividirValores(){
            double valor1 = Double.parseDouble(txtValor1.getText());
    double valor2 = Double.parseDouble(txtValor2.getText());

    if(valor2 == 0){
        JOptionPane.showMessageDialog(null, "Error: No se puede dividir entre cero");
        return;
    }

    Calculadora cal = new Calculadora();
    Double respuesta = cal.dividir(valor1, valor2);
    txtRespuesta.setText(respuesta +"");
    }
    
    // ==========================
    // LIMPIAR CAMPOS
    // ==========================

    private void limpiarCampos(){
        txtValor1.setText("");
        txtValor2.setText("");
        txtRespuesta.setText("");
        txtValor1.requestFocus();
        
    } 
    
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
              new CalculadoraGUI().setVisible(true);
            }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblValor1;
    private javax.swing.JButton btnConversor2;
    private javax.swing.JButton btnConversorTemperatura;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnMultiplicar4;
    private javax.swing.JButton btnPotencia;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnResetear;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lblRespuestas;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JPanel plOperaciones;
    private javax.swing.JPanel plTitulo;
    private javax.swing.JPanel plValores;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables

}
